import{a as p,S as m,i}from"./assets/vendor-w8Z1wSTr.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const y="https://pixabay.com/api/",g="51688063-4461a08693fd836abbdb4b603";async function h(s){const r={key:g,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0},{data:t}=await p.get(y,{params:r});return t}const c=document.querySelector(".gallery"),u=document.querySelector(".loader"),b=new m(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function v(s){const r=s.map(({webformatURL:t,largeImageURL:n,tags:e,likes:o,views:a,comments:d,downloads:f})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${n}">
          <img class="gallery-image" src="${t}" alt="${e}" />
        </a>
        <div class="stat-container">
          <div><span><b>Likes</b></span><span>${o}</span></div>
          <div><span><b>Views</b></span><span>${a}</span></div>
          <div><span><b>Comments</b></span><span>${d}</span></div>
          <div><span><b>Downloads</b></span><span>${f}</span></div>
        </div>
      </li>`).join("");c.insertAdjacentHTML("beforeend",r),b.refresh()}function L(){c.innerHTML=""}function w(){u.style.display="inline-block"}function q(){u.style.display="none"}const l=document.querySelector(".form");l.addEventListener("submit",async s=>{s.preventDefault();const r=s.target.elements["search-text"].value.trim();if(!r){i.show({message:"Input field can not be empty. Please enter your query.",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight"});return}L(),w();try{const t=await h(r);if(!t.hits||t.hits.length===0){i.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight"});return}v(t.hits)}catch(t){i.show({message:`Error: ${(t==null?void 0:t.message)||t}`,messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight"})}finally{q(),l.reset()}});
//# sourceMappingURL=index.js.map
